### ISSUE TITLE
Incorrect y-axis labels in If item dropped posterior plots

### ISSUE THREAD

**Issue by vandenman** [juliuspf/reliabilityBayesian#3]
![image](https://user-images.githubusercontent.com/21319932/81797065-9465c600-950e-11ea-8f0c-1e2fb70182c9.png)

even though the names in the tables are different:

![image](https://user-images.githubusercontent.com/21319932/81797087-9af43d80-950e-11ea-9130-396b07cad6f0.png)

**Comment by juliuspf** [comment]
fixed.
