### ISSUE TITLE
JASP objects do not have a "position" argument

### ISSUE THREAD

**Issue by vandenman** [juliuspf/reliabilityBayesian#4]
### To replicate the issue
1. Tick `R-hat`
2. Tick `Plot Posteriors`
3. Untick `R-hat`
4. Tick `R-hat`

After 2, the position of R-hat is before that of the posterior plots. After 4. it is below the plots. 

### Solution
Each jaspObject has a `$position` (that can also be set in the constructor) that you can use to fix the positions. If you don't do this the order can become messy.

Also, for R-hat specifically, I'd add this as an additional column to the main table (Bayesian Scale Reliability Statistics).

**Comment by juliuspf** [comment]
fixed.
