### ISSUE TITLE
Names for sampling parameters differ from JAGS

### ISSUE THREAD

**Issue by vandenman** [juliuspf/reliabilityBayesian#6]
I'd also change `Traceplots` to `Trace plots`. The rest is optional though it would be nice to be consistent:

JAGS:
![image](https://user-images.githubusercontent.com/21319932/81797878-9f6d2600-950f-11ea-84e6-0be8a1c3ef15.png)

Bayesian Reliability:
![image](https://user-images.githubusercontent.com/21319932/81797924-abf17e80-950f-11ea-81bf-ed29a7bdb639.png)

Also, for some reason the width of the first DoubleField (no. of posterior samples) is different from the other ones.

**Comment by juliuspf** [comment]
fixed.
